language: c

branches:
  only:
    - master

install:
  - source devtools/ci/install.sh
  - export PYTHONUNBUFFERED=true

script:
  # this builds the binary, unpacks it, and runs the tests
  - conda build devtools/conda-recipe
  # Push to binstar.

env:
  matrix:
    - python=2.7  CONDA_PY=27
#    - python=3.3  CONDA_PY=33
#    - python=3.4  CONDA_PY=34

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "JJLc73pllLW3FwDxmIWxizKItLOCbYHfqIQjkRQ6Z59x5ZP2KiDh37QdsHbQ7Rbq+6g+P10odFiZ2ynnqAhs/SOVo6TNkKb0kdcNzfrlTjZLDba7Pf5y8HWAXGqwy8sQWpS8n/wdXRzG6eQ+3td2P+EaQNa1AfsoHnMFhvzrhKU="
    # encrypted AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    - secure: "SrSd1JoI8dBXQxDAX0xBTYBinTusRBQoPETnxHrBAgKdoty1pkzaghTKNMsrGsk78iwkkj1hAyttIY9trdFQkmx+OTx0fLKFmDHsMkgko4RzTtrgLgoxuRIs/gruID2cN1XKEbxlhRmQF14+q8/X1q6iGGdYMrxo51JcYPuEOSo="
    - secure: "br6QRMYXhHltYTEh/d+zejxcunT3GsqwQvxxLmqnLxi+LIxX4j7eymR6p4fPBd5mCRxyvkQEjnSZxF6e7JlEKxWVcMG28I/dBWzVIRW3EKQQNRmyI+JL1dfNaqj68kHJD+FknBwHK9LD238JPcyqXPdVrm9iPkDijPczvPBxvDs="
after_success:
  - echo "after_success"
  - bash devtools/ci/after_sucess.sh
