package:
  name: yank
  version: !!str 0.0.0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt

  run:
    - python
    - pandas
    - scipy
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

