package:
  name: yank-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]

requirements:
  build:
    - python
    - cython
    - setuptools

  run:
    - python
    - pandas
    - numpy >=1.14
    - scipy
    - cython
    - netcdf4 >=1.4.2 # after bugfix: "always return masked array by default, even if there are no masked values"
    - libnetcdf >=4.6.2 # workaround for libssl issues
    - openmm >=7.3
    - mdtraj >=1.7.2
    - openmmtools >=0.15.0
    - pymbar
    - ambermini >=16.16.0
    - docopt
    - openmoltools >=0.7.5
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - cerberus ==1.1.*
    - matplotlib
    - jupyter
    - pdbfixer

about:
  home: https://github.com/choderalab/yank
  license: MIT
