package:
  name: yank-dev
  version: !!str 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools >=0.7.2
    - pymbar
    - ambermini
    - docopt
    - openmoltools
    - sphinxcontrib-bibtex
    - alchemy >=1.1.3
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm
    - openmmtools >=0.7.2
    - pymbar
    - ambermini
    - docopt
    - openmoltools
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy >=1.1.3
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
    - openmmtools
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
