package:
  name: yank-dev
  version: !!str 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm-dev
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools-dev
    - pymbar ==2.1beta0
    - ambermini >=15.0.4
    - docopt
    - openmoltools-dev
    - sphinxcontrib-bibtex
    - alchemy-dev
    - schema >=0.5.0
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm-dev
    - mdtraj 1.5.1 # TODO remove me when segment_id bug is fixed (this is installed through openmoltools)
    - openmmtools-dev
    - pymbar ==2.1beta0
    - ambermini >=15.0.4
    - docopt
    - openmoltools-dev
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy-dev
    - schema >=0.5.0
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help
    - yank selftest

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
