package:
  name: yank-dev
  version: !!str 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm >=7.0.1
    - mdtraj >=1.7.2
    - openmmtools
    - pymbar
    - ambermini >=15.0.4
    - docopt
    - openmoltools
    - sphinxcontrib-bibtex
    - alchemy
    - schema >=0.6.2
    #- gcc 4.8.2 # [linux]
    #- gcc 4.8.2 # [osx]

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm >=7.0.1
    - mdtraj >=1.7.2
    - openmmtools
    - pymbar
    - ambermini >=15.0.4
    - docopt
    - openmoltools
    - mpi4py
    - pyyaml
    - clusterutils
    - sphinxcontrib-bibtex
    - alchemy
    - schema >=0.6.2
    #- libgcc

test:
  requires:
    - nose
    - nose-timer
  imports:
    - yank
  commands:
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
