package:
  name: yank
  version: !!str 0.0.0

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt
    - gaff2xml
    - jinja2

  run:
    - python
    - pandas
    - numpy
    - scipy
    - cython
    - netcdf4
    - openmm
    - openmmtools
    - pymbar
    - ambermini
    - docopt
    - gaff2xml
    - mpi4py
    - pyyaml
    - jinja2
    - cluster_utils    

test:
  requires:
    - nose
  imports:
    - yank
  commands:
    - nosetests yank --nocapture --verbosity=2 --with-doctest
    - which yank
    - yank --help

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)




