package:
  name: yank
  version: !!str 0.0.0


requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - netcdf4
    - mdtraj
    - gaff2xml
    - repex
    - openmm
    - openmmtools
    - pymbar
    - ambermini

  run:
    - python
    - pandas
    - scipy
    - netcdf4
    - mdtraj
    - gaff2xml
    - repex
    - openmm
    - openmmtools
    - pymbar
    - ambermini

about:
  home: https://github.com/choderalab/yank
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

